Add `dedi_sendPrintsToClient` to server convars
R2Northstar/NorthstarWiki pull request #184
Opened 2023-05-10 13:25 UTC by CooldudePUGS

Ngl, kind of just guessing and writing based off of https://github.com/R2Northstar/NorthstarLauncher/pull/418 as I don't have a way to test this myself (no access to ports), probably needs to have changes suggested by someone because of this

Closes #150

2023-05-10 13:37 UTC, ASpoonPlaysGames requested changes
Description makes sense, but from looking at the code and doing my own testing there are some inaccuracies in the values:

- -1 -> no prints are sent to clients
- 0 -> prints are sent to the first client only
- 1 -> prints are sent to all clients

default value is -1 (no prints)

2023-05-10 13:46 UTC, CooldudePUGS commented
threw something together quickly because ive got class here in a second

2023-05-17 09:52 UTC, GeckoEidechse commented on docs/hosting-a-server-with-northstar/dedicated-server/README.md
> +| `dedi_sendPrintsToClient`                        | Whether the dedicated server should forward all logs to connected clients, which is useful for testing/debugging on a dedicated server. If -1, sen
```suggestion
| `dedi_sendPrintsToClient`                        | Whether the dedicated server should forward all logs to connected clients, which is useful for testing/debugging on a dedicated server. If `-1`, send no prints to clients. If `0`, send prints to the first client connected only. If `1`, send prints to all clients                                                                   | `-1`                            | `-1-1`                                             |
```

2023-05-24 15:40 UTC, GeckoEidechse commented on docs/hosting-a-server-with-northstar/dedicated-server/README.md
> +| `dedi_sendPrintsToClient`                        | Whether the dedicated server should forward all logs to connected clients, which is useful for testing/debugging on a dedicated server. If `-1`, s
Note sure if I wanna remove the sentence

> `which is useful for testing/debugging on a dedicated server`

to maintain table size of just keep it at the cost of technically having to resize table in source...

2023-05-30 15:14 UTC, itscynxx commented on docs/hosting-a-server-with-northstar/dedicated-server/README.md
> +| `dedi_sendPrintsToClient`                        | Whether the dedicated server should forward all logs to connected clients, which is useful for testing/debugging on a dedicated server. If `-1`, s
Do we want to remove this line? Don't feel like much is lost if we do, most people wanting to use this probably know what to use it for. Not really sure what `having to resize table in source` means

2023-07-21 17:57 UTC, GeckoEidechse commented on docs/hosting-a-server-with-northstar/dedicated-server/README.md
> +| `dedi_sendPrintsToClient`                        | Whether the dedicated server should forward all logs to connected clients, which is useful for testing/debugging on a dedicated server. If `-1`, s
Welp kinda overlooked that one. Just gonna merge as is for now I guess

2023-07-21 17:57 UTC, GeckoEidechse approved these changes
The table is kinda not properly formatted in source now but should be fine.

2023-07-21 17:58 UTC, merged