Change docs to prefer northstar for publishing
R2Northstar/NorthstarWiki pull request #43
Opened 2022-02-06 19:47 UTC by laundmo

Describes uploading to Thunderstore by default instead of the discord channel.

2022-02-06 20:44 UTC, GeckoEidechse requested changes

2022-02-06 20:44 UTC, GeckoEidechse commented on docs/modding/publishing.md
> +- `manifest.json` outlined here: https://northstar.thunderstore.io/package/create/docs/
```suggestion
- `manifest.json` outlined [here](https://northstar.thunderstore.io/package/create/docs/)
```

2022-02-06 20:44 UTC, GeckoEidechse commented on docs/modding/publishing.md
> +manifest.json checker: https://northstar.thunderstore.io/tools/manifest-v1-validator/
```suggestion
manifest.json checker: [https://northstar.thunderstore.io/tools/manifest-v1-validator/](https://northstar.thunderstore.io/tools/manifest-v1-validator/)
```

Gitbook doesn't auto detect links sadly, so doing it like this is necessary to make a link clickable.

2022-02-06 20:44 UTC, GeckoEidechse commented on docs/modding/publishing.md
> +After you have set up the folder structure, head to https://northstar.thunderstore.io and log in with either Discord or Github. Then you can use the Upload button at the top to upload your zip.
```suggestion
After you have set up the folder structure, head to [https://northstar.thunderstore.io](https://northstar.thunderstore.io) and log in with either Discord or Github. Then you can use the _Upload_ button at the top of the page to upload your zip.
```

2022-02-06 20:44 UTC, GeckoEidechse commented on docs/modding/publishing.md
> +When uploading, it will verify your package structure and you can publish after its successfully checked.
```suggestion
When uploading, it will verify your package structure and you can publish after it's successfully checked.
```

2022-02-07 13:46 UTC, merged

2022-02-07 14:51 UTC, xamionex commented
Northstar for publishing :-)

2022-02-07 15:49 UTC, GeckoEidechse commented
Fuck I also missed that. Should've said "_Thunderstore_". Oh well ¯\\\_(ツ)\_/¯