Removed all modding-related content and moved it to RTD
R2Northstar/NorthstarWiki pull request #53
Opened 2022-02-15 20:16 UTC by emma-miler

Removed all modding-related content and moved it to [ReadTheDocs](https://r2northstar.readthedocs.io).
Already checked for backlinks and updated them.

2022-02-15 21:24 UTC, GeckoEidechse commented
Blocking until [R2Northstar/ModdingDocs](https://github.com/R2Northstar/ModdingDocs) gets a proper README :3

2022-02-25 09:15 UTC, emma-miler commented
It has a README now, not sure if you think it's proper :P

2022-02-25 10:09 UTC, GeckoEidechse commented
You're still missing a license though :P

2022-02-25 10:10 UTC, emma-miler commented
Good point, i'll copy it over from this repo and fix the merge conflicts

2022-03-18 23:19 UTC, GeckoEidechse requested changes

2022-03-18 23:19 UTC, GeckoEidechse commented on docs/SUMMARY.md
>    * [Getting Started](modding/getting-started.md)
You missed a line :3

```suggestion
```

2022-03-18 23:19 UTC, GeckoEidechse commented on docs/modding/localisation_files.md
> -To test your modifications go to `Origin (My games library) -> Titanfall 2 (right click) -> Game Properties -> Advanced Launch Options` and select the language you modified from the dropdown.
Do we have localisation instructions in the new modding docs? Couldn't find any :c

2022-03-23 13:33 UTC, Alystrasz commented
@emma-miler please finish your PR :smiley: 

(asking for a friend btw)
![Capture d’écran de 2022-03-23 14-31-19](https://user-images.githubusercontent.com/11993538/159711167-4e6c4943-fcf4-4239-b2e1-38d625868ae7.png)

2022-03-27 01:03 UTC, emma-miler commented
Updated

2022-03-27 01:08 UTC, GeckoEidechse approved these changes

2022-03-27 01:09 UTC, merged